server:
  port: 8090
spring:
  application:
    name: baseProject
    port:
  datasource:
    url: jdbc:mysql://192.168.145.128:3306/mp
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
knife4j:
  enable: true
  openapi:
    title: 基础项目接口文档
    description: "基础项目接口文档"
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.clear.controller
ocean:
  auth:
    excludePaths:
      - /user/login
  jwt:
    location: classpath:ocean.jks
    alias: 123456
    password: 123456
    tokenTTL: 30m
logging:
  level:
    com.clear.ocean: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler #枚举类型转换